---
title: "Explorando a APi"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r, warning=FALSE}
library(tidyverse)
library(lubridate)
library(jsonlite)
library(zoo)
#devtools::install_github("juliasilge/silgelib")
library(silgelib)
#install.packages("viridis")
library(viridis)
theme_set(theme_roboto())
# These fonts must be installed locally on your computer for this theme to work: https://fonts.google.com/specimen/Roboto+Condensed and https://fonts.google.com/specimen/Roboto. 

source('../R/intimidade.R')
```

# Counts

##  Usando a API

```{r carrega_da_api}
# vistos_raw = fromJSON("http://150.165.85.12:41205/get_last_minutes?m=129600") %>% 
#     as.tibble() %>% 
#     filter(identifier == "LSD") %>% 
#     select(-3)
# 
# vistos = vistos_raw %>% 
#     mutate(t = ymd_hms(timestamp)) %>% 
#     select(-timestamp)
# perenes = get_macs_perenes(vistos)
# 
# vistos = vistos %>% 
#     filter(!(mac %in% perenes$mac))

```

## A partir do Dump

```{r}
vistos = read_csv("../data/db_lsd_sem_perenes.csv", 
                  col_types = cols(
                    t = col_datetime(format = ""),
                    mac = col_character(),
                    signal = col_integer()
                ))

# contagem = conta_macs(vistos, 5)
contagem = read_csv("../data/contagem_lsd.csv")
```


```{r "ao longo do dia"}
# contagem = conta_macs(vistos, 5)
# write_csv(contagem, "../data/contagem_lsd.csv")
contagem = read_csv("../data/contagem_lsd.csv")

janela_suavizacao = 15

suavizada = contagem %>% 
    mutate(dia = floor_date(periodo, unit = "day"), 
           hora = (hour(periodo) * 60 + minute(periodo)) / 60, 
           n_smooth = rollapply(n, janela_suavizacao , mean, align='right', fill=NA)) %>% 
    group_by(dia) %>% 
    filter(n() > 12 * (60/janela_suavizacao)) %>% # 12 horas com obs a cada 5 mins
    ungroup() %>% 
    filter(complete.cases(.))
```


```{r}
gglinhas_dos_dias = function(contagem_suavizada){
    contagem_suavizada %>% 
        ggplot(aes(x = hora, y = n_smooth, group = dia)) + 
        geom_line(alpha = .15, size = .6, color = "#CC1900") + 
        #scale_y_sqrt() + 
        scale_x_continuous(breaks = c(8, 12, 14, 16, 18, 20), limits = c(7, 23)) + 
        labs(x = "hora do dia", 
             y = "pessoas pelo hall", 
             title = "Nossos dias",
             subtitle = "Cada linha é um dia da gente convivendo no hall")  %>% 
        return()
}

p = suavizada %>% 
    filter(wday(dia) %in% 2:6) %>% 
    gglinhas_dos_dias() 
p
ggsave("dias-geral.png", dpi = 300, width = 7, height = 5)

```

```{r}
library(viridis)
suavizada %>% 
    #filter(month(periodo) > 8, year(periodo) > 2015) %>%
    ggplot(aes(x = hora, y = n_smooth, group = dia, colour = month(periodo))) + 
    geom_line(alpha = .2, size = 1) + 
    scale_y_sqrt() + 
    scale_color_viridis(NULL, option = "A", direction = -1) +
    xlim(8, 20) + 
    labs(x = "hora do dia", 
         y = "pessoas pelo hall", 
         title = "Nossos dias",
         subtitle = "Cada linha é um dia da gente convivendo no hall") + 
    coord_polar() 
```


```{r}
p = suavizada %>% 
    mutate(dia_semana = wday(dia, label = TRUE)) %>%
    mutate(dia_semana = factor(dia_semana, 
                               labels = c("Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"))) %>% 
    gglinhas_dos_dias() + 
    facet_grid(dia_semana ~ .) + 
    #xlim(6, 24) + 
    labs(title = "Nem todo dia é igual",
         subtitle = "Na semana a gente muda")  
    
p
ggsave("dias-da-semana.png", dpi = 300, width = 6, height = 15)
```

```{r}
p = suavizada %>% 
    filter(year(dia) == 2016, wday(dia) %in% 2:6) %>% 
    ggplot(aes(x = hora, y = n_smooth, group = dia, color = month(dia))) + 
    geom_line(alpha = .2, size = .7) + 
    scale_x_continuous(breaks = c(8, 12, 16, 18, 20), limits = c(7, 23)) +
    scale_color_viridis(option = "magma", direction = -1) + 
    labs(x = "hora do dia", 
         y = "pessoas", 
         title = "Nossos dias",
         subtitle = "Cada linha é um dia. A gente convivendo no hall.")
p
```


```{r}
# pdf("teste.pdf")
suavizada %>% 
    mutate(dia_semana = wday(dia, label = TRUE)) %>%
    mutate(dia_semana = factor(dia_semana, 
                               labels = c("Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"))) %>% 
        ggplot(aes(x = floor(hora), y = n_smooth, group = floor(hora))) + 
        geom_boxplot(color = "#CC1900", outlier.shape = NA) + 
        facet_grid(dia_semana ~ .) + 
        scale_x_continuous(breaks = c(8, 12, 14, 16, 18, 20), limits = c(7, 23)) + 
        scale_y_continuous(limits = quantile(suavizada$n_smooth, c(0.05, 0.95)))
        labs(x = "hora do dia", 
             y = "pessoas", 
             title = "Nossos dias",
             subtitle = "Cada linha é um dia. A gente convivendo no hall.")
# dev.off()
```


## Dias especiais

Procurar: 
17-02-2016 21h

16-09-2016 15h30
27-09-2016 17h30

17-10-2016
18-10-2016 17h

09-12-2016  20h   20 anos
17-06-2016  20h   SJ



```{r}
ggplot_dia_destaque <- function(dados, 
                                dia_especial, 
                                label_dia, 
                                sublabel_dia,
                                cor_sem_destaque, 
                                cor_destaque) {
    dados %>% 
        ggplot(aes(x = hora, y = n_smooth, group = dia)) + 
        geom_line(alpha = .25, size = .6, color = cor_sem_destaque) +
        scale_x_continuous(breaks = c(8, 12, 16, 18, 20), limits = c(7, 24)) + 
        geom_line(data = filter(suavizada, date(dia) == ymd(dia_especial)), 
                  alpha = .9, 
                  color = cor_destaque,
                  size = 2) +
        labs(x = "hora do dia", 
             y = "pessoas", 
             title = label_dia,
             subtitle = sublabel_dia)  %>% 
        return()
}


dia_especial = "2016-06-17"
label_dia = "Nosso São João 2016"
sublabel_dia = "Aqui. Parece que teve também no PP"
cor_sem_destaque = "#00B29D"
cor_destaque = "#FF4F00"

p = suavizada %>% 
    ggplot_dia_destaque(dia_especial, 
                        label_dia, 
                        sublabel_dia, 
                        cor_sem_destaque, 
                        cor_destaque =  "#B23904")
p
ggsave("dias-sj.png", dpi = 300, width = 7, height = 5)
```


```{r}
p = suavizada %>% 
    ggplot_dia_destaque(dia_especial = "2016-12-09", 
                        label_dia = "Comemoração dos 20 anos do LSD!!", 
                        sublabel_dia = ":D", 
                        cor_sem_destaque, 
                        cor_destaque = "#FF4F00")
p 
ggsave("dias-20anos.png", dpi = 300, width = 7, height = 5)
```

# No calendário

```{r}
p = suavizada %>% 
    filter(year(dia) == 2016) %>% 
    ggplot(aes(x = yday(dia), 
               fill = sqrt(n_smooth), 
               y = hour(periodo))) + 
    geom_tile() +
    #facet_wrap(~month(dia)) + 
    scale_fill_viridis() + 
    ylim(7, 22) + 
    labs(x = "dia do ano", 
         y = "hora", 
         title = "Os dias mudando ao longo de 2016",
         subtitle = "Cores mais claras são mais gente pelo hall") + 
    theme(legend.position = "none")
p 

ggsave("dias-do-ano.png", dpi = 300, width = 21, height = 4)
```

```{r}
#mixed sort gtools
p = suavizada %>% 
    filter(year(dia) == 2016) %>%
    filter(wday(dia) %in% 2:6) %>% 
    mutate(mes = month(dia, label = T), 
           hora = floor(hour(periodo)), 
           dia_semana = wday(dia, label = T)) %>% 
    group_by(mes, dia_semana, hora) %>% 
    summarise(n_smooth = mean(n_smooth)) %>% 
    ggplot(aes(x = hora, 
               fill = sqrt(n_smooth), 
               y = dia_semana)) + 
    geom_tile() +
    coord_flip() + 
    facet_wrap(~mes) +
    xlim(7, 23) + 
    scale_fill_viridis(option = "inferno") + 
    labs(x = "hora do dia", 
         y = "dia da semana", 
         title = "Em que dia/hora da semana mais socializamos?",
         subtitle = "Em que horário nosso espaço de encontro estava mais vivo?")  + 
    theme(legend.position = "None")
p 

ggsave("hora-da-semana.png", dpi = 300, width = 10, height = 8)
```


## Almoço 

```{r}
suavizada %>% 
    filter(hora > 11.8, hora < 14, year(periodo) < 2017) %>% 
    group_by(quando = floor_date(periodo, unit = "week")) %>% 
    summarise(comum = mean(n)) %>% 
    ggplot(aes(x = quando, y = comum)) + 
    geom_point() + 
    geom_smooth()
```

# Relógio, versão dia

```{r}
suavizada %>%
    filter(year(periodo) == 2016) %>%
    ggplot(aes(x = hora, y = n_smooth, group = dia, color = month(periodo))) + 
    geom_line(alpha = .13, size = .7) +
    scale_color_viridis(NULL, direction = -1, begin = 0.1, end = 1, option = "B") +
    scale_x_continuous(breaks = seq(8, 19, 1), limits = c(7, 19)) +
    scale_y_sqrt() +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size=23, family = "Helvetica", face = "bold", colour = "gray30"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank())
```


# Relógio, versão noite

```{r}
suavizada %>%
    filter(year(periodo) == 2016) %>%
    ggplot(aes(x = hora, y = n_smooth, group = dia, color = month(periodo))) + 
    geom_line(alpha = .13, size = .7) +
    scale_color_viridis(NULL, direction = -1, begin = 0.1, end = 1, option = "D") +
    scale_x_continuous(breaks = seq(8, 19, 1), limits = c(7, 19)) +
    scale_y_sqrt() +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size=23, family = "Helvetica", face = "bold", colour = "gray30"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank())
```


# Relógio sem a legenda

```{r}
suavizada %>%
    filter(year(periodo) == 2016) %>%
    ggplot(aes(x = hora, y = n_smooth, group = dia, color = month(periodo))) + 
    geom_hline(alpha = 0.7, yintercept = c(5, 20, 45, 75, 115), colour = "gray80", size = 1) +
    geom_line(alpha = .15, size = .7) +
    annotate("text", label = "5", x = 20, y = 5, size = 7, family = "Helvetica", fontface = "bold", color = "gray70") +
    annotate("text", label = "15", x = 20, y = 20, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "45", x = 20, y = 45, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "75", x = 20, y = 75, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "5", x = 14, y = 5, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "15", x = 14, y = 20, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "45", x = 14, y = 45, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "75", x = 14, y = 75, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "5", x = 11, y = 5, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "15", x = 11, y = 20, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "45", x = 11, y = 45, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "75", x = 11, y = 75, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "5", x = 17, y = 5, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "15", x = 17, y = 20, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "45", x = 17, y = 45, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "75", x = 17, y = 75, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    scale_color_viridis(NULL, direction = -1, begin = 0.1, option = "D") +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_y_sqrt() + 
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 54, family = "Helvetica", face = "bold", colour = "gray60"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          panel.grid = element_blank(),
                          legend.position = "none")
```



```{r}
suavizada %>%
    filter(year(periodo) == 2016) %>%
    mutate(mes = cut(month(periodo), breaks = 4, labels = c("Jan-Mar", "Abr-Jun", "Jul-Set", "Out-Dez"))) %>%
    ggplot(aes(x = hora, y = n_smooth, group = dia, color = mes)) + 
    geom_hline(alpha = 0.7, yintercept = c(5, 20, 45, 75, 115), colour = "gray80", size = 1) +
    geom_line(alpha = .15, size = .7) +
    annotate("text", label = "5", x = 20, y = 5, size = 7, family = "Helvetica", fontface = "bold", color = "gray70") +
    annotate("text", label = "15", x = 20, y = 20, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "45", x = 20, y = 45, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    annotate("text", label = "75", x = 20, y = 75, size = 7, family = "Helvetica", fontface = "bold", color = "gray60") +
    scale_color_viridis(NULL, direction = -1, begin = 0.1, option = "D", discrete = T) +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_y_sqrt() + 
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 54, family = "Helvetica", face = "bold", colour = "gray60"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          panel.grid = element_blank(),
                          legend.position = c(0.5, 0.21),
                          legend.background = element_rect(color = "gray80", linetype = "solid")) +
    guides(color = guide_legend(override.aes = list(size=3, alpha = 1)))
```


```{r}
suavizada %>%
    filter(year(periodo) == 2016) %>%
    group_by(hour(periodo)) %>%
    mutate(atividade.min = quantile(n_smooth, probs = 0.1),
           atividade.max = quantile(n_smooth, probs = 0.7),
           atividade.media = median(n_smooth)) %>%
    ggplot(aes(x = hora, ymin = atividade.min, ymax = atividade.max, color = atividade.media)) +
    geom_linerange(size = 1.3, alpha = 0.75) +
    scale_y_sqrt(limits = c(-5, 50)) +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_color_viridis(NULL, option = "A", direction = -1) +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 16, family = "Helvetica", colour = "gray60"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          panel.grid.major.x = element_blank())
```

# Relógio oficial simples

```{r}
set.seed(23)

contagens.2016 <- suavizada %>%
    filter(year(periodo) == 2016, wday(periodo) %in% 2:6)

dados.grafico.principal <- contagens.2016 %>%
    group_by(hora) %>%
    summarise(atividade.min = quantile(n_smooth, probs = 0.1),
           atividade.max = quantile(n_smooth, probs = 0.95),
           atividade.media = median(n_smooth))

dados.grafico.extremos <- contagens.2016 %>%
    group_by(hora) %>%
    mutate(atividade.media = median(n_smooth)) %>%
    ungroup() %>%
    filter(n_smooth > quantile(n_smooth, 0.95))

ggplot() +
    geom_hline(alpha = 0.5, yintercept = c(5, 20, 45), colour = "gray90", size = 0.8) +
    geom_linerange(data = dados.grafico.principal, aes(x = hora, ymin = atividade.min, ymax = atividade.max, color = atividade.media), size = 1.3, alpha = 0.75) +
    #geom_jitter(data = dados.grafico.extremos, aes(x = hora, y = n_smooth, group = dia, color = atividade.media), alpha = 0.35, size = 1.3, width = 0.3, height = 0) +
    #geom_line(data = dados.grafico.extremos, aes(x = hora, y = n_smooth, group = dia, color = atividade.media), alpha = 0.35, size = 1.3) +
    geom_point(data = dados.grafico.principal, aes(x = hora, y = atividade.media), color = "white", alpha = .5, size = 1) +
    annotate("text", label = "NOSSA ATIVIDADE", x = 20, y = 45, size = 10, family = "Helvetica", fontface = "bold", color = "#21908CFF") +
    annotate("text", label = "pessoas no/perto do hall ao longo do dia", x = 20, y = 37, size = 5, family = "Helvetica", color = "gray70") +
    annotate("text", label = "5", x = 14, y = 5, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "20", x = 20, y = 20, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "45", x = 14, y = 45, size = 5, family = "Helvetica", color = "gray80") +
    #annotate("text", label = "75", x = 14, y = 75, size = 5, family = "Helvetica", color = "gray80") +
    scale_y_sqrt() +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_color_viridis(NULL, end = 0.97) +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 34, family = "Helvetica", face = "bold", colour = "gray70"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          #panel.grid = element_blank(),
                          legend.position = "none")

ggsave("nosso-relogio.pdf", width = 10, height = 10)
```




```{r}
set.seed(23)

contagens.2016 <- suavizada %>%
    filter(year(periodo) == 2016, wday(periodo) %in% 2:6)

dados.grafico.principal <- contagens.2016 %>%
    group_by(hora) %>%
    summarise(atividade.min = quantile(n_smooth, probs = 0.1),
           atividade.max = quantile(n_smooth, probs = 0.9),
           atividade.media = median(n_smooth))

dados.grafico.extremos <- contagens.2016 %>%
    filter(n_smooth > quantile(n_smooth, 0.999))

ggplot() +
    geom_hline(alpha = 0.5, yintercept = c(5, 20, 45, 75), colour = "gray90", size = 0.8) +
    geom_linerange(data = dados.grafico.principal, aes(x = hora, ymin = atividade.min, ymax = atividade.max, color = atividade.media), size = 1.3, alpha = 0.75) +
    geom_jitter(data = dados.grafico.extremos, aes(x = hora, y = n_smooth, group = dia), alpha = 0.35, size = 2, width = 0.3, height = 0.3, color = "#FED799FF") +
    annotate("text", label = "5", x = 20, y = 5, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "15", x = 20, y = 20, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "45", x = 20, y = 45, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "75", x = 20, y = 75, size = 5, family = "Helvetica", color = "gray80") +
    scale_y_sqrt() +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_color_viridis(NULL, option = "A", end = 0.97) +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 34, family = "Helvetica", face = "bold", colour = "gray60"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          panel.grid = element_blank(),
                          legend.position = "none")
```


# Relógio oficial completo

```{r}
set.seed(23)

contagens.2016 <- suavizada %>%
    filter(year(periodo) == 2016, wday(periodo) %in% 2:6)

dados.grafico.principal <- contagens.2016 %>%
    group_by(hora) %>%
    summarise(atividade.min = quantile(n_smooth, probs = 0.1),
           atividade.max = quantile(n_smooth, probs = 0.9),
           atividade.media = median(n_smooth))

dados.grafico.extremos <- contagens.2016 %>%
    filter(n_smooth > quantile(n_smooth, 0.99))

ggplot() +
    geom_hline(alpha = 0.5, yintercept = c(5, 20, 45, 75, 115), colour = "gray90", size = 0.8) +
    geom_linerange(data = dados.grafico.principal, aes(x = hora, ymin = atividade.min, ymax = atividade.max, color = atividade.media), size = 1.3, alpha = 0.75) +
    geom_jitter(data = dados.grafico.extremos, aes(x = hora, y = n_smooth, group = dia), alpha = 0.4, size = 2, width = 0.3, height = 0.3, color = "#FED799FF") +
    geom_line(data = dados.grafico.principal, aes(x = hora, y = atividade.media, color = atividade.media)) +
    annotate("text", label = "5", x = 20, y = 5, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "15", x = 20, y = 20, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "45", x = 20, y = 45, size = 5, family = "Helvetica", color = "gray80") +
    annotate("text", label = "75", x = 20, y = 75, size = 5, family = "Helvetica", color = "gray80") +
    scale_y_sqrt() +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_color_viridis(NULL, option = "A", end = 0.97) +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 32, family = "Helvetica", face = "bold", colour = "gray60"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          panel.grid = element_blank(),
                          legend.position = c(0.5, 0.21),
                          legend.background = element_rect(color = "gray80", linetype = "solid"))
```



```{r}
suavizada %>%
    filter(year(periodo) == 2016) %>%
    group_by(mes = month(periodo, label = T), hora) %>%
    summarise(atividade.min = quantile(n_smooth, probs = 0.1),
           atividade.max = quantile(n_smooth, probs = 0.9),
           atividade.media = median(n_smooth)) %>%
    ggplot(aes(x = hora, ymin = atividade.min, ymax = atividade.max, color = atividade.media)) + facet_wrap(~mes) +
    geom_linerange(size = 1.3, alpha = 0.75) +
    scale_y_sqrt() +
    scale_x_continuous(breaks = seq(9, 20, 1), limits = c(8, 20)) +
    scale_color_viridis(NULL, option = "A", end = 0.9) +
    coord_polar() + theme(axis.title.x = element_blank(),
                          axis.text.x = element_text(size = 16, family = "Helvetica", colour = "gray60"),
                          axis.title.y = element_blank(),
                          axis.text.y = element_blank(),
                          panel.grid = element_blank())
```

