---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE, include=FALSE}

library(tidyverse)
library(lubridate)
library(jsonlite)
#devtools::install_github("juliasilge/silgelib")
library(silgelib)
library(knitr)
theme_set(theme_roboto())

source("../R/intimidade.R")

opts_knit$set(cache = F)
```

Carrega os dados

```{r}

db <- read.csv("../data/db_lsd_sem_perenes.csv") %>%
    mutate(t = ymd_hms(t))

intimidade <- read.csv("../data/intimidade.csv")
names(intimidade) <- c("timestamp", "nome", "mac", "mensagem")
intimidade <- intimidade %>%
    select(-1) %>%
    mutate(mac = tolower(mac))

conhecidos <- merge(db, intimidade, by = "mac")
dias_semana <- c("Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab")

```

Identifica os madrugões e corujões 

```{r}

madrugoes <- db %>%
    filtra_pessoas_por_horario(4, 8) %>%
    agrupa_presencas_por_dia_da_semana() %>%
    filtra_diferentoes()


c1 <- filtra_pessoas_por_horario(db, 20, 24)
c2 <- filtra_pessoas_por_horario(db, 0, 4)
corujoes <- rbind(c1, c2) %>%
    agrupa_presencas_por_dia_da_semana() %>%
    filtra_diferentoes()
remove(c1, c2)

```


Merge com intimidade

```{r}
madrugoes.conhecidos <- merge(madrugoes, intimidade, by = "mac")
corujoes.conhecidos <- merge(corujoes, intimidade, by = "mac")
```



```{r}
conhecidos_por_semana <- conhecidos %>%
    agrupa_presencas_por_dia_da_semana() %>%
    merge(intimidade, by = "mac")

atividade_semanal <- conhecidos_por_semana %>%
    group_by(mac) %>%
    summarise(presenca.total = sum(presenca))

conhecidos_por_semana %>%
    merge(atividade_semanal, by = "mac") %>%
    mutate(proporcao.presenca = presenca / presenca.total) %>%
    mutate(dia = factor(dia, levels = 1:7, labels = dias_semana)) %>%
    ggplot(aes(x = dia, y = proporcao.presenca, group = mac, fill = mensagem)) + 
    geom_area() + theme(legend.position = "none") + facet_wrap(~mensagem) + labs(title = "Ícones da presença", x = "Dia da semana", y = "Proporção da presença")
```

















```{r}
trabalhadores_diurnos <- db %>%
    filtra_pessoas_por_horario(6, 18) %>%
    agrupa_presencas_por_dia_da_semana() %>%
    merge(intimidade, by = "mac")

trabalhadores_noturnos <- db %>%
    filtra_pessoas_por_horario(18, 24) %>%
    agrupa_presencas_por_dia_da_semana() %>%
    merge(intimidade, by = "mac")
```


```{r}
atividade_semanal_diurna <- trabalhadores_diurnos %>%
    group_by(mac) %>%
    summarise(presenca.total = sum(presenca))

trabalhadores_diurnos %>%
    merge(atividade_semanal_diurna, by = "mac") %>%
    mutate(proporcao.presenca = presenca / presenca.total) %>%
    mutate(dia = factor(dia, levels = 1:7, labels = dias_semana)) %>%
    ggplot(aes(x = dia, y = proporcao.presenca, group = mac, fill = mensagem)) + 
    geom_area() + theme(legend.position = "none") + facet_wrap(~mensagem) + labs(title = "Ícones da presença diurna", x = "Dia da semana", y = "Proporção da presença")
```

```{r}
atividade_semanal_noturna <- trabalhadores_noturnos %>%
    group_by(mac) %>%
    summarise(presenca.total = sum(presenca))

trabalhadores_noturnos %>%
    merge(atividade_semanal_noturna, by = "mac") %>%
    mutate(proporcao.presenca = presenca / presenca.total) %>%
    mutate(dia = factor(dia, levels = 1:7, labels = dias_semana)) %>%
    ggplot(aes(x = dia, y = proporcao.presenca, group = mac, fill = mensagem)) + 
    geom_area() + theme(legend.position = "none") + facet_wrap(~mensagem) + labs(title = "Ícones da presença noturna", x = "Dia da semana", y = "Proporção da presença")
```




```{r}
atividade_conhecidos <- conhecidos %>% 
    mutate(t = ymd_hms(t)) %>%
    group_by(mensagem, dia_f = floor_date(t, unit = "day")) %>%
    filter(t == first(t)) %>% 
    ungroup() %>% 
    mutate(dia = wday(t)) %>%
    group_by(mensagem, dia) %>% 
    count()

atividade_por_pessoa <- atividade_conhecidos %>%
    group_by(mensagem) %>%
    summarise(somadias = sum(n))
```

```{r}
 atividade_conhecidos %>%
    merge(atividade_por_pessoa, by = "mensagem") %>%
    mutate(taxa_atividade = n / somadias) %>%
    ggplot(aes(x = dia, y = taxa_atividade)) + 
    geom_line() + facet_wrap(~mensagem) + labs(title = "Dias favoritos pra visitar o lab", y = "Frequência (%)", x = "Dia da semana") + theme_minimal()
```
