---
title: "Relação entre a Temperatura e a quantidade de pessoas"
output: html_notebook
---


```{r}
library("dplyr")
library("ggplot2")
setwd("~/nossa-intimidade/")
knitr::opts_chunk$set(echo = TRUE)
dados <- read.csv("../data/temperatura_macs.csv")
theme_set(theme_bw())

```

```{r}
lm_eqn = function(m) {
  l <- list(a = format(coef(m)[1], digits = 2),
      b = format(abs(coef(m)[2]), digits = 2),
      r2 = format(summary(m)$r.squared, digits = 3));

  if (coef(m)[2] >= 0)  {
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2,l)
  } else {
    eq <- substitute(italic(y) == a - b %.% italic(x)*","~~italic(r)^2~"="~r2,l)    
  }

  as.character(as.expression(eq));                 
}

pdf("scatter-macs-temperatura.pdf", width = 6, height = 4)

ggplot(dados, aes(x=num_macs, y=Temp.Comp.Media)) +
    geom_jitter(width = .2, height = .2, alpha = .6) + 
    geom_smooth(method=lm) +
    annotate("text", y = 20, x = 12, label = lm_eqn(lm(num_macs ~ Temp.Comp.Media, dados)), parse = TRUE) + 
    labs(y="Temperatura ºC", x="Quantidade de MACs") 
dev.off()

cor.test(dados$Temp.Comp.Media, dados$num_macs)

```

